objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact_First_Name__c</fullName>
        <label>Contact First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Last_Name__c</fullName>
        <label>Contact Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navitaire_Id__c</fullName>
        <externalId>true</externalId>
        <label>Navitaire Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Corporate</fullName>
        <active>true</active>
        <description>For Corporate Accounts</description>
        <label>Corporate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Central Coordinator</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Created_in_Navitaire__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created in Navitaire</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Email_AS__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name_AS__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name_AS__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navitaire_Id__c</fullName>
        <externalId>true</externalId>
        <label>Navitaire Id</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Phone_AS__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product_Role__c</fullName>
        <label>Product/Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>API Corporate</fullName>
                </value>
                <value>
                    <fullName>CORT</fullName>
                </value>
                <value>
                    <fullName>HOL</fullName>
                </value>
                <value>
                    <fullName>IBM</fullName>
                </value>
                <value>
                    <fullName>LTC</fullName>
                </value>
                <value>
                    <fullName>STBF</fullName>
                </value>
                <value>
                    <fullName>TATA</fullName>
                </value>
                <value>
                    <fullName>TCPN</fullName>
                </value>
                <value>
                    <fullName>Web Travel Agent</fullName>
                </value>
                <value>
                    <fullName>APIC</fullName>
                </value>
                <value>
                    <fullName>GRP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Title_AS__c</fullName>
        <label>Title</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Corporate</fullName>
        <active>true</active>
        <businessProcess>Corporate</businessProcess>
        <description>For Corporate leads</description>
        <label>Corporate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Product__c.object
<CustomObject>
    <description>To track Products offered to Travel Agencies.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_in_Navitaire__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created in Navitaire</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Navitaire_ID__c</fullName>
        <externalId>true</externalId>
        <label>Navitaire ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Product_Role__c</fullName>
        <label>Product/Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>API Corporate</fullName>
                </value>
                <value>
                    <fullName>CORT</fullName>
                </value>
                <value>
                    <fullName>HOL</fullName>
                </value>
                <value>
                    <fullName>IBM</fullName>
                </value>
                <value>
                    <fullName>LTC</fullName>
                </value>
                <value>
                    <fullName>STBF</fullName>
                </value>
                <value>
                    <fullName>TATA</fullName>
                </value>
                <value>
                    <fullName>TCPN</fullName>
                </value>
                <value>
                    <fullName>Web Travel Agent</fullName>
                </value>
                <value>
                    <fullName>APIC</fullName>
                </value>
                <value>
                    <fullName>GRP</fullName>
                </value>
                <value>
                    <fullName>RETAIL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Approved by Central Coordinator</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>PR-{0000}</displayFormat>
        <label>Record No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LeadTriggerHandler.cls
/*
* Name        : LeadTriggerHandler
* Description : LeadTriggerHandler is a Trigger handler class for LeadTriggers
                Functions : 
                1.  To covert Lead
                2.  To mandate Central Coordinators to update Navitaire Id before approving the Lead
* Author      : Himanshu Maheshwari
* Create On   : 03 September 2016
*  |-------------------------------------------------------------------------|
*  | Version | Modified By      | Date       | Comment                       |
*  |-------------------------------------------------------------------------|
*  | 0.1     | Himanshu         | 03/09/2016 | Initial Version of Class      |
*  |-------------------------------------------------------------------------|
*/
public class LeadTriggerHandler {
    public LeadTriggerHandler(Boolean isExecuting, Integer size) {

    }

    public void OnBeforeUpdate(List<Lead> newLeadlist, Map<Id, Lead> oldLeadMap) {
        for (Lead ld : newLeadlist) {
            if (String.isBlank(ld.Navitaire_Id__c) && ld.Approval_Status__c == 'Approved by Central Coordinator' && ld.Approval_Status__c != oldLeadMap.get(ld.Id).Approval_Status__c){
                ld.addError(System.Label.Enter_Navitaire_Id_Error_Message);
            }
        }
    }

    public void OnAfterUpdate(List<Lead> newLeadlist, Map<Id, Lead> oldLeadMap) {
        List<Lead> LeadList = new List<Lead>();
        for (Lead ld : newLeadlist) {
            //if(ld.Approval_Status__c == 'Approved' && ld.Navitaire_Id__c != NULL && oldLeadMap.get(ld.Id).Navitaire_Id__c == NULL) {
            if(ld.Approval_Status__c == 'Approved' && ld.Created_in_Navitaire__c == TRUE && oldLeadMap.get(ld.Id).Created_in_Navitaire__c == FALSE) {
                leadList.add(ld);
            }            
        }

        if(leadList.size() > 0)
                ConvertLead(leadList);
    }

    public void ConvertLead(List<Lead> leadList){
        LeadStatus convertStatus = [SELECT MasterLabel FROM LeadStatus where IsConverted = TRUE limit 1];
        List<Contact> cnctList = new List<Contact>();
        List<Account> accList = new List<Account>();
        List<Product__c> prdList = new List<Product__c>();

        for(Lead ld : leadList){
            Database.LeadConvert lc = new Database.LeadConvert();
            lc.setDoNotCreateOpportunity(TRUE);
            lc.setConvertedStatus(convertStatus.MasterLabel);
            lc.setLeadId(ld.Id);
            
            Database.LeadConvertResult lcr = Database.convertLead(lc);
            System.assert(lcr.isSuccess());

            Account acc = new Account(Id = lcr.getAccountId());
            acc.Contact_First_Name__c = ld.First_Name_AS__c;
            acc.Contact_Last_Name__c = ld.Last_Name_AS__c;
            accList.add(acc);

            //if(Schema.Sobjecttype.Lead.getRecordTypeInfosByName().get('Corporate').getRecordTypeId() == ld.RecordTypeId){
            Contact cnct = new Contact();
            cnct.AccountId = lcr.getAccountId();
            cnct.FirstName = ld.First_Name_AS__c;
            cnct.LastName = ld.Last_Name_AS__c;
            cnct.Title = ld.Title_AS__c;
            cnct.MobilePhone = ld.Phone_AS__c;
            cnct.Email = ld.Email_AS__c;
            cnctList.add(cnct);
            //}

            Product__c pr = new Product__c();
            pr.Account__c = lcr.getAccountId();
            pr.Navitaire_ID__c = ld.Navitaire_Id__c;
            pr.Product_Role__c = ld.Product_Role__c;
            pr.Status__c = ld.Approval_Status__c;
            pr.Created_in_Navitaire__c = ld.Created_in_Navitaire__c;
            pr.OwnerId = ld.OwnerId;
            prdList.add(pr);
        }

        if(accList.size() > 0)
            update accList;

        if(cnctList.size() > 0)
            insert cnctList;

        if(prdList.size() > 0)
            insert prdList;
    }
}