objects/Booking__c.object
<CustomObject>
    <description>To track customer bookings coming from Datamart</description>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Journey_Date__c</fullName>
        <label>Last Journey Date</label>
        <summarizedField>Journey_Detail__c.Arrival_Time__c</summarizedField>
        <summaryForeignKey>Journey_Detail__c.Booking__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Cases_Associated__c</fullName>
        <label>Total Cases Associated</label>
        <summarizedField>Journey_Detail__c.Total_number_of_cases__c</summarizedField>
        <summaryFilterItems>
            <field>Journey_Detail__c.Total_number_of_cases__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>Journey_Detail__c.Booking__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>PNR No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Emails_for_Email_Notification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of all Email Id for Email Notifications</description>
    <fields>
        <fullName>To_Email_Addresses__c</fullName>
        <label>To Email Addresses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Emails for Email Notification</label>
</CustomObject>

objects/Maximum_Record_Retention__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Bookings__c</fullName>
        <label>Bookings</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Maximum Record Retention (in Months)</label>
</CustomObject>

classes/DeleteBookingBatch.cls
/*
 * Name        : DeleteBookingBatch
 * Description : DeleteBookingBatch is a batch apex class function is to automatically purge the 
                 Booking records after a certain peroid if no case is associated with it.
 * Author      : Himanshu Maheshwari
 * Create On   : 07 June 2016
 *  |-------------------------------------------------------------------------|
 *  | Version | Modified By      | Date       | Comment                       |
 *  |-------------------------------------------------------------------------|
 *  | 0.1     | Himanshu         | 07/06/2016 | Initial Version of Class      |
 *  |-------------------------------------------------------------------------|
 */
global class DeleteBookingBatch implements Database.Batchable<sObject>, Database.Stateful {
    global String query; 
    global Integer count = 0;
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Maximum_Record_Retention__c maxRet = Maximum_Record_Retention__c.getInstance('Retention Period');
        Datetime dt = Datetime.newInstance(System.today().toStartOfMonth().addMonths(-(Integer)maxRet.Bookings__c), Time.newInstance(0, 0, 0, 0));

        query = 'SELECT Id, Total_Cases_Associated__c FROM Booking__c WHERE (Total_Cases_Associated__c = NULL OR Total_Cases_Associated__c = 0) AND (Last_Journey_Date__c <: dt OR Last_Journey_Date__c = NULL) AND Booking_Date__c <: dt';
        System.debug('Query ::::::::::' + query);
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<Booking__c> scope) {
        count += scope.size();
        delete scope;
    }

    global void finish(Database.BatchableContext BC) {
        System.debug('Total Number of Booking records deleted ----- '+ count);
        AsyncApexJob a = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                          FROM AsyncApexJob WHERE Id =: BC.getJobId()];

        Emails_for_Email_Notification__c delBookingEmailList = Emails_for_Email_Notification__c.getValues('Booking Deletion Batch');
        // Send an Email Notification.
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = delBookingEmailList.To_Email_Addresses__c.split(',');
        mail.setToAddresses(toAddresses);
        mail.setSubject('Booking Deletion Batch ' + a.Status);
        mail.setPlainTextBody('The Booking Deletion Batch processed. Total number of Booking records deleted - '+ count);
        
        if(!Test.isRunningTest()){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }    
}