objects/Booking__c.object
<CustomObject>
    <description>To track customer bookings coming from Datamart</description>
    <fields>
        <fullName>Booked_By__c</fullName>
        <label>Booked By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking_Id__c</fullName>
        <externalId>true</externalId>
        <label>Booking Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>PNR No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Passenger__c.object
<CustomObject>
    <description>to capture the Passenger details</description>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CreateCustomerExtTest.cls
/*
 * Name        : CreateCustomerExt 
 * Description : CreateCustomerExt is a Extension class for CreateCustomer Visualforce. 
                 Purpose is to initiate Create Customer from Passenger Flow
 * Author      : Himanshu Maheshwari
 * Create On   : 21 June 2016
 *  |-------------------------------------------------------------------------|
 *  | Version | Modified By      | Date       | Comment                       |
 *  |-------------------------------------------------------------------------|
 *  | 0.1     | Himanshu         | 21/06/2016 | Initial Version of Class      |
 *  |-------------------------------------------------------------------------|
 */
@isTest
public class CreateCustomerExtTest {
    public static testMethod void  tagEntitlmenttoCase(){
        
        Account acc = new Account();
        acc.LastName = 'Test Name';
        insert acc;

        Booking__c b = new Booking__c();
        b.Booked_By__c = acc.Id;
        b.Booking_Id__c = '224512';
        //b.Booking_Date__c = System.today();
        insert b;

        Passenger__c pssngr = new Passenger__c();
        pssngr.Booking__c = b.Id;
        pssngr.Name = 'Test First Name';
        pssngr.Last_Name__c = 'Test Last Name';
        insert pssngr;
      
        ApexPages.StandardController sc = new ApexPages.StandardController(pssngr);
        CreateCustomerExt ccExt = new CreateCustomerExt(sc);
        ccExt.createCustFlow = new Flow.Interview.Create_Customer_from_Passenger(new Map<String, Object>());
        ccExt.CreateCustomer();
    }
}