objects/Booking__c.object
<CustomObject>
    <description>To track customer bookings coming from Datamart</description>
    <fields>
        <fullName>Booked_By__c</fullName>
        <label>Booked By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking_Id__c</fullName>
        <externalId>true</externalId>
        <label>Booking Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking_Status__c</fullName>
        <label>Booking Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active and Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>PNR No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Journey_Detail__c.object
<CustomObject>
    <description>To track the flight details of the Booking</description>
    <fields>
        <fullName>Arrival_Station__c</fullName>
        <label>Arrival Station</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Journey Details</relationshipLabel>
        <relationshipName>Journey_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Departure_Station__c</fullName>
        <label>Departure Station</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Journey_Number__c</fullName>
        <label>Journey Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <label>Leg Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Journey Detail</label>
    <nameField>
        <label>Flight No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Passenger__c.object
<CustomObject>
    <description>to capture the Passenger details</description>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Passengers</relationshipLabel>
        <relationshipName>Passengers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Passenger</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passengers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerController__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To manage trigger using checkbox-make acive/deactive</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to activate/deactivate trigger</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerController</label>
</CustomObject>

classes/Bulk_BIR_CtrTest.cls
/*
 * Name        : Bulk_BIR_CtrTest 
 * Description : Bulk_BIR_CtrTest is a test class for Extension class Bulk_BIR_Ctr. 
               : Himanshu Maheshwari
 * Create On   : 15 Sept 2016
 *  |-------------------------------------------------------------------------|
 *  | Version | Modified By      | Date       | Comment                       |
 *  |-------------------------------------------------------------------------|
 *  | 0.1     | Himanshu         | 15/09/2016 | Initial Version of Class      |
 *  |-------------------------------------------------------------------------|
 */
@isTest
public class Bulk_BIR_CtrTest {
    public static testMethod void  Bulk_BIR_CtrTest(){

        TriggerController__c tController = new TriggerController__c();
        tController.Name = 'AccountTrigger';
        tController.IsActive__c = TRUE;
        insert tController;

        TriggerController__c tController1 = new TriggerController__c();
        tController1.Name = 'CaseTrigger';
        tController1.IsActive__c = TRUE;
        insert tController1;
        
        Account acc = new Account();
        acc.FirstName = 'test';
        acc.LastName = 'Last';
        acc.PersonHomePhone = '98745102';
        acc.Home_Phone_Type__pc = 'Mobile';
        acc.Contact__pc = '9874102563';
        insert acc;
        
        Booking__c b = new Booking__c();
        b.Name = '1212012';
        b.Booked_By__c = acc.Id;
        b.Booking_Date__c = datetime.now();
        b.Booking_Id__c = '74512086';
        b.Booking_Status__c = 'Active';
        insert b;

        Journey_Detail__c j = new Journey_Detail__c();
        j.Name = '516';
        j.Arrival_Station__c = 'BOM';
        j.Arrival_Time__c = datetime.now();
        j.Booking__c = b.Id;
        j.Departure_Station__c = 'DEL';
        j.Departure_Time__c = datetime.now();
        j.Journey_Number__c = '1';
        j.Leg_Number__c = '2';
        insert j;

        Passenger__c pssngr = new Passenger__c();
        pssngr.Booking__c = b.Id;
        pssngr.Name = 'Test First Name';
        pssngr.Last_Name__c = 'Test Last Name';
        insert pssngr;
      
        Bulk_BIR_Ctr bb = new Bulk_BIR_Ctr();
        bb.flight_Number = '516';
        bb.departure_Date = date.today();
        bb.arrival_Date = date.today();
        bb.ce.Arrival_Station__c = 'BOM';
        bb.ce.Departure_Station__c = 'DEL';
        bb.SearchFlightDetail();
        bb.custDetailsList[0].isBaggageLost = TRUE;
        bb.CreateBIRCases();
    }
}