objects/Booking__c.object
<CustomObject>
    <description>To track customer bookings coming from Datamart</description>
    <fields>
        <fullName>Booked_By__c</fullName>
        <label>Booked By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>PNR No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Arrival_Station__c</fullName>
        <label>Arrival Station</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PNR_Record__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adampur(VIAX)</fullName>
                </value>
                <value>
                    <fullName>Agartala (IXA)</fullName>
                </value>
                <value>
                    <fullName>Ahmedabad (AMD)</fullName>
                </value>
                <value>
                    <fullName>Aizawl (AJL)</fullName>
                </value>
                <value>
                    <fullName>Amritsar (ATQ)</fullName>
                </value>
                <value>
                    <fullName>Bagdogra (IXB)</fullName>
                </value>
                <value>
                    <fullName>Bangkok (BKK)</fullName>
                </value>
                <value>
                    <fullName>Belagavi (IXG)</fullName>
                </value>
                <value>
                    <fullName>Bengaluru (BLR)</fullName>
                </value>
                <value>
                    <fullName>Chandigarh (IXC)</fullName>
                </value>
                <value>
                    <fullName>Chennai (MAA)</fullName>
                </value>
                <value>
                    <fullName>Coimbatore (CJB)</fullName>
                </value>
                <value>
                    <fullName>Colombo (CMB)</fullName>
                </value>
                <value>
                    <fullName>Dehradun (DED)</fullName>
                </value>
                <value>
                    <fullName>Delhi (DEL)</fullName>
                </value>
                <value>
                    <fullName>Dhaka(DAC)</fullName>
                </value>
                <value>
                    <fullName>Dharamshala (DHM)</fullName>
                </value>
                <value>
                    <fullName>Dibrugarh (DIB)</fullName>
                </value>
                <value>
                    <fullName>Dubai (DXB)</fullName>
                </value>
                <value>
                    <fullName>Goa (GOI)</fullName>
                </value>
                <value>
                    <fullName>Gorakhpur (GOP)</fullName>
                </value>
                <value>
                    <fullName>Guwahati (GAU)</fullName>
                </value>
                <value>
                    <fullName>Hyderabad (HYD)</fullName>
                </value>
                <value>
                    <fullName>Jabalpur (JLR)</fullName>
                </value>
                <value>
                    <fullName>Jaipur (JAI)</fullName>
                </value>
                <value>
                    <fullName>Jaisalmer(JSA)</fullName>
                </value>
                <value>
                    <fullName>Jammu (IXJ)</fullName>
                </value>
                <value>
                    <fullName>Jodhpur (JDH)</fullName>
                </value>
                <value>
                    <fullName>Kabul (KBL)</fullName>
                </value>
                <value>
                    <fullName>Kandla(IXY)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Created_by_Bulk_BIR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created by Bulk BIR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Airport Services</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Cockpit</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Engineering/ MCC</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>FSC</fullName>
                </value>
                <value>
                    <fullName>Guest Error</fullName>
                </value>
                <value>
                    <fullName>In- Flight</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Legal/HR</fullName>
                </value>
                <value>
                    <fullName>Marketing/ Products</fullName>
                </value>
                <value>
                    <fullName>Reservation Administration</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
                <value>
                    <fullName>SalesRevenue</fullName>
                    <label>Sales/Revenue</label>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>SpiceVacation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Departure_Station__c</fullName>
        <label>Departure Station</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PNR_Record__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adampur(VIAX)</fullName>
                </value>
                <value>
                    <fullName>Agartala (IXA)</fullName>
                </value>
                <value>
                    <fullName>Ahmedabad (AMD)</fullName>
                </value>
                <value>
                    <fullName>Aizawl (AJL)</fullName>
                </value>
                <value>
                    <fullName>Amritsar (ATQ)</fullName>
                </value>
                <value>
                    <fullName>Bagdogra (IXB)</fullName>
                </value>
                <value>
                    <fullName>Bangkok (BKK)</fullName>
                </value>
                <value>
                    <fullName>Belagavi (IXG)</fullName>
                </value>
                <value>
                    <fullName>Bengaluru (BLR)</fullName>
                </value>
                <value>
                    <fullName>Chandigarh (IXC)</fullName>
                </value>
                <value>
                    <fullName>Chennai (MAA)</fullName>
                </value>
                <value>
                    <fullName>Coimbatore (CJB)</fullName>
                </value>
                <value>
                    <fullName>Colombo (CMB)</fullName>
                </value>
                <value>
                    <fullName>Dehradun (DED)</fullName>
                </value>
                <value>
                    <fullName>Delhi (DEL)</fullName>
                </value>
                <value>
                    <fullName>Dhaka(DAC)</fullName>
                </value>
                <value>
                    <fullName>Dharamshala (DHM)</fullName>
                </value>
                <value>
                    <fullName>Dibrugrah(DIB)</fullName>
                </value>
                <value>
                    <fullName>Dubai (DXB)</fullName>
                </value>
                <value>
                    <fullName>Goa (GOI)</fullName>
                </value>
                <value>
                    <fullName>Gorakhpur (GOP)</fullName>
                </value>
                <value>
                    <fullName>Guwahati (GAU)</fullName>
                </value>
                <value>
                    <fullName>Hyderabad (HYD)</fullName>
                </value>
                <value>
                    <fullName>Jabalpur (JLR)</fullName>
                </value>
                <value>
                    <fullName>Jaipur (JAI)</fullName>
                </value>
                <value>
                    <fullName>Jaisalmer(JSA)</fullName>
                </value>
                <value>
                    <fullName>Jammu (IXJ)</fullName>
                </value>
                <value>
                    <fullName>Jodhpur (JDH)</fullName>
                </value>
                <value>
                    <fullName>Kabul (KBL)</fullName>
                </value>
                <value>
                    <fullName>Kandla(IXY)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Flight_Record__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight Record</label>
        <referenceTo>Journey_Detail__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PNR_No__c</fullName>
        <label>PNR No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>BIR</fullName>
        <active>true</active>
        <businessProcess>BIR Support Process</businessProcess>
        <description>For Baggage Irregularity Reports</description>
        <label>BIR</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey_Detail__c.object
<CustomObject>
    <description>To track the flight details of the Booking</description>
    <fields>
        <fullName>Arrival_Date__c</fullName>
        <formula>DATEVALUE( Arrival_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Arrival Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Arrival_Station__c</fullName>
        <label>Arrival Station</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Journey Details</relationshipLabel>
        <relationshipName>Journey_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Departure_Date__c</fullName>
        <formula>DATEVALUE( Departure_Time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Departure Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departure_Station__c</fullName>
        <label>Departure Station</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PNR_No__c</fullName>
        <label>PNR No.</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Journey Detail</label>
    <nameField>
        <label>Flight No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Bulk_BIR_Ctr.cls
public class Bulk_BIR_Ctr {
    public String flight_Number {get; set;}
    public Date arrival_Date {get; set;}
    public Date departure_Date {get; set;}
    public List <CustomerWrapper> custDetailsList {get; set;}
    public List <Account> accList {get; set;}
    public Boolean selectAll {get; set;}
    public Boolean birCreated {get; set;}
    public Boolean disableCreateBIR {get; set;}
    public List <Case> caseList {get; set;}
    public Case ce {get; set;}
       
    public Bulk_BIR_Ctr() {
        disableCreateBIR = FALSE;
        ce = new Case(Department__c = 'Airport Services');
        caseList = new List<Case>();
        custDetailsList = new List<CustomerWrapper>();
        accList = new List<Account>();
    }

    public void SearchFlightDetail(){
        Set <String> uniqueBookedBySet = new Set <String>();
        caseList = new List<Case>();
        custDetailsList = new List<CustomerWrapper>();
        
        for(Journey_Detail__c jDetail : [SELECT Id, PNR_No__c, Booking__r.Booked_By__r.PersonContactId, Booking__r.Booked_By__c, Booking__r.Booked_By__r.Name, Arrival_Station__c, Arrival_Time__c, Departure_Station__c, Departure_Time__c, Name FROM Journey_Detail__c WHERE Name =: flight_Number AND Arrival_Date__c =: arrival_Date AND Departure_Date__c =: departure_Date AND Arrival_Station__c =: ce.Arrival_Station__c AND Departure_Station__c =: ce.Departure_Station__c]){
            if(!uniqueBookedBySet.contains(jDetail.Booking__r.Booked_By__r.Name)){
                CustomerWrapper cWrap = new CustomerWrapper(jDetail);
                custDetailsList.add(cWrap);
                uniqueBookedBySet.add(jDetail.Booking__r.Booked_By__r.Name);
            }
        }
    }
    
    public void CreateBIRCases(){
        for(CustomerWrapper cWrap : custDetailsList){
            if(cWrap.isBaggageLost){
                Case cs = new Case();
                cs.RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByName().get('BIR').getRecordTypeId();
                cs.ContactId = cWrap.jDetail.Booking__r.Booked_By__r.PersonContactId ;
                cs.Flight_Record__c = cWrap.jDetail.Id;
                cs.Created_by_Bulk_BIR__c = TRUE;
                cs.Type = 'Complaint';
                cs.Origin = 'Airport';
                cs.Department__c = ce.Department__c;
                cs.Category__c = ce.Category__c;
                caseList.add(cs);
            }
        }

        if(caseList.size() > 0)
            insert caseList;
            
        caseList = [SELECT Id, CaseNumber, PNR_No__c, ContactId, Contact.Name FROM Case WHERE Id IN: caseList];
            
        custDetailsList = new List <CustomerWrapper>();
        disableCreateBIR = TRUE;
    }
    
    public class CustomerWrapper{
        public Boolean isBaggageLost {get; set;}
        public Journey_Detail__c jDetail {get; set;}
        public CustomerWrapper(Journey_Detail__c jDetail){
            this.isBaggageLost = FALSE;
            this.jDetail = jDetail;
        }
    }
}