objects/Booking__c.object
<CustomObject>
    <description>To track customer bookings coming from Datamart</description>
    <fields>
        <fullName>Booked_By__c</fullName>
        <label>Booked By</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Booking_Date__c</fullName>
        <label>Booking Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking_Id__c</fullName>
        <externalId>true</externalId>
        <label>Booking Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking_Status__c</fullName>
        <label>Booking Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
                <value>
                    <fullName>Active and Updated</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>PNR No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Arrival_Station__c</fullName>
        <label>Arrival Station</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PNR_Record__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adampur(VIAX)</fullName>
                </value>
                <value>
                    <fullName>Agartala (IXA)</fullName>
                </value>
                <value>
                    <fullName>Ahmedabad (AMD)</fullName>
                </value>
                <value>
                    <fullName>Aizawl (AJL)</fullName>
                </value>
                <value>
                    <fullName>Amritsar (ATQ)</fullName>
                </value>
                <value>
                    <fullName>Bagdogra (IXB)</fullName>
                </value>
                <value>
                    <fullName>Bangkok (BKK)</fullName>
                </value>
                <value>
                    <fullName>Belagavi (IXG)</fullName>
                </value>
                <value>
                    <fullName>Bengaluru (BLR)</fullName>
                </value>
                <value>
                    <fullName>Chandigarh (IXC)</fullName>
                </value>
                <value>
                    <fullName>Chennai (MAA)</fullName>
                </value>
                <value>
                    <fullName>Coimbatore (CJB)</fullName>
                </value>
                <value>
                    <fullName>Colombo (CMB)</fullName>
                </value>
                <value>
                    <fullName>Dehradun (DED)</fullName>
                </value>
                <value>
                    <fullName>Delhi (DEL)</fullName>
                </value>
                <value>
                    <fullName>Dhaka(DAC)</fullName>
                </value>
                <value>
                    <fullName>Dharamshala (DHM)</fullName>
                </value>
                <value>
                    <fullName>Dibrugarh (DIB)</fullName>
                </value>
                <value>
                    <fullName>Dubai (DXB)</fullName>
                </value>
                <value>
                    <fullName>Goa (GOI)</fullName>
                </value>
                <value>
                    <fullName>Gorakhpur (GOP)</fullName>
                </value>
                <value>
                    <fullName>Guwahati (GAU)</fullName>
                </value>
                <value>
                    <fullName>Hyderabad (HYD)</fullName>
                </value>
                <value>
                    <fullName>Jabalpur (JLR)</fullName>
                </value>
                <value>
                    <fullName>Jaipur (JAI)</fullName>
                </value>
                <value>
                    <fullName>Jaisalmer(JSA)</fullName>
                </value>
                <value>
                    <fullName>Jammu (IXJ)</fullName>
                </value>
                <value>
                    <fullName>Jodhpur (JDH)</fullName>
                </value>
                <value>
                    <fullName>Kabul (KBL)</fullName>
                </value>
                <value>
                    <fullName>Kandla(IXY)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Airport Services</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Cockpit</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Engineering/ MCC</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>FSC</fullName>
                </value>
                <value>
                    <fullName>Guest Error</fullName>
                </value>
                <value>
                    <fullName>In- Flight</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Legal/HR</fullName>
                </value>
                <value>
                    <fullName>Marketing/ Products</fullName>
                </value>
                <value>
                    <fullName>Reservation Administration</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
                <value>
                    <fullName>SalesRevenue</fullName>
                    <label>Sales/Revenue</label>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>SpiceVacation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Departure_Station__c</fullName>
        <label>Departure Station</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>PNR_Record__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Adampur(VIAX)</fullName>
                </value>
                <value>
                    <fullName>Agartala (IXA)</fullName>
                </value>
                <value>
                    <fullName>Ahmedabad (AMD)</fullName>
                </value>
                <value>
                    <fullName>Aizawl (AJL)</fullName>
                </value>
                <value>
                    <fullName>Amritsar (ATQ)</fullName>
                </value>
                <value>
                    <fullName>Bagdogra (IXB)</fullName>
                </value>
                <value>
                    <fullName>Bangkok (BKK)</fullName>
                </value>
                <value>
                    <fullName>Belagavi (IXG)</fullName>
                </value>
                <value>
                    <fullName>Bengaluru (BLR)</fullName>
                </value>
                <value>
                    <fullName>Chandigarh (IXC)</fullName>
                </value>
                <value>
                    <fullName>Chennai (MAA)</fullName>
                </value>
                <value>
                    <fullName>Coimbatore (CJB)</fullName>
                </value>
                <value>
                    <fullName>Colombo (CMB)</fullName>
                </value>
                <value>
                    <fullName>Dehradun (DED)</fullName>
                </value>
                <value>
                    <fullName>Delhi (DEL)</fullName>
                </value>
                <value>
                    <fullName>Dhaka(DAC)</fullName>
                </value>
                <value>
                    <fullName>Dharamshala (DHM)</fullName>
                </value>
                <value>
                    <fullName>Dibrugrah(DIB)</fullName>
                </value>
                <value>
                    <fullName>Dubai (DXB)</fullName>
                </value>
                <value>
                    <fullName>Goa (GOI)</fullName>
                </value>
                <value>
                    <fullName>Gorakhpur (GOP)</fullName>
                </value>
                <value>
                    <fullName>Guwahati (GAU)</fullName>
                </value>
                <value>
                    <fullName>Hyderabad (HYD)</fullName>
                </value>
                <value>
                    <fullName>Jabalpur (JLR)</fullName>
                </value>
                <value>
                    <fullName>Jaipur (JAI)</fullName>
                </value>
                <value>
                    <fullName>Jaisalmer(JSA)</fullName>
                </value>
                <value>
                    <fullName>Jammu (IXJ)</fullName>
                </value>
                <value>
                    <fullName>Jodhpur (JDH)</fullName>
                </value>
                <value>
                    <fullName>Kabul (KBL)</fullName>
                </value>
                <value>
                    <fullName>Kandla(IXY)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Journey_Detail__c.object
<CustomObject>
    <description>To track the flight details of the Booking</description>
    <fields>
        <fullName>Arrival_Station__c</fullName>
        <label>Arrival Station</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Booking__c</fullName>
        <label>Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipLabel>Journey Details</relationshipLabel>
        <relationshipName>Journey_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Departure_Station__c</fullName>
        <label>Departure Station</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Departure_Time__c</fullName>
        <label>Departure Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Journey_Number__c</fullName>
        <label>Journey Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Leg_Number__c</fullName>
        <label>Leg Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Journey Detail</label>
    <nameField>
        <label>Flight No.</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Journey Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerController__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To manage trigger using checkbox-make acive/deactive</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to activate/deactivate trigger</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerController</label>
</CustomObject>

classes/CaseTest.cls
@isTest
public class CaseTest {
    public static testMethod void  tagEntitlmenttoCase() {

        TriggerController__c tController = new TriggerController__c();
        tController.Name = 'CaseTrigger';
        tcontroller.IsActive__c = true;
        insert tController;

        Account acc = new Account();
        acc.FirstName = 'test';
        acc.LastName = 'Last';
        acc.PersonHomePhone = '98745102';
        acc.Home_Phone_Type__pc = 'Mobile';
        acc.Contact__pc = '9874102563';
        insert acc;
        
        Booking__c b = new Booking__c();
        b.Name = '1212012';
        b.Booked_By__c = acc.Id;
        b.Booking_Date__c = datetime.now();
        b.Booking_Id__c = '74512086';
        b.Booking_Status__c = 'Active';
        insert b;

        Journey_Detail__c j = new Journey_Detail__c();
        j.Name = 'SJ-321';
        j.Arrival_Station__c = 'BOM';
        j.Arrival_Time__c = datetime.now();
        j.Booking__c = b.Id;
        j.Departure_Station__c = 'DEL';
        j.Departure_Time__c = datetime.now();
        j.Journey_Number__c = '1';
        j.Leg_Number__c = '2';
        insert j;

        Profile p = [SELECT Id FROM Profile WHERE Name = 'Customer Experience'];
        User u = new User(Alias = 'standt', Email = 'testuser@spicejettestorg.com',
                          EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
                          LocaleSidKey = 'en_US', ProfileId = p.Id,
                          TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testuser@spicejettestorg.com');

        System.runAs(u) {
            // The following code runs as user 'u'
            System.debug('Current User: ' + UserInfo.getUserName());
            System.debug('Current Profile: ' + UserInfo.getProfileId());

            Case testCase = new Case(Department__c = 'Catering',
                                     Category__c = 'Catering - Meal Quality',
                                     //testcase.Sub_Category__c='';
                                     //testcase.Sub_Department__c='';
                                     Status = 'New',
                                     Origin = 'Phone',
                                     Type = 'Complaint'
                                    );
            insert testcase;

            Case testCase2 = new Case(Department__c = 'Catering',
                                      Category__c = 'Catering - Meal Quality',
                                      //testcase.Sub_Category__c='';
                                      //testcase.Sub_Department__c='';
                                      Status = 'New',
                                      Origin = 'Phone',
                                      Type = 'Complaint',
                                      Flight_Record__c = j.Id
                                     );
            insert testcase2;

            Case testCase3 = new Case(Department__c = 'Catering',
                                      Category__c='Catering - Meal Quality',
                                      //testcase.Sub_Category__c='';
                                      //testcase.Sub_Department__c='';
                                      Status = 'New',
                                      Origin = 'Phone',
                                      Type = 'Complaint'
                                     );
            insert testcase3;

            Case testCase4 = new Case(Department__c = 'Miscellaneous',
                                      //Category__c='Catering - Meal Quality',
                                      Sub_Category__c = 'Service Complaint',
                                      Sub_Department__c = 'Travel Portals/Travel Agents',
                                      Status = 'New',
                                      Origin = 'Phone',
                                      Type = 'Complaint'
                                     );
            insert testcase4;

            testcase.Department__c = 'Engineering/ MCC';
            testcase.Category__c = 'Aircraft Interior';
            testcase.Flight_Record__c = j.Id;
            update testCase;
        }
    }
}