objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AC not working</fullName>
                </value>
                <value>
                    <fullName>Add-ons Issue</fullName>
                </value>
                <value>
                    <fullName>Aircraft Interior</fullName>
                </value>
                <value>
                    <fullName>Ancillary Revenue</fullName>
                </value>
                <value>
                    <fullName>Atom IVR</fullName>
                </value>
                <value>
                    <fullName>Bad Landing</fullName>
                </value>
                <value>
                    <fullName>Bad Landing/Complaint</fullName>
                </value>
                <value>
                    <fullName>Baggage Exchange</fullName>
                </value>
                <value>
                    <fullName>Baggage Interchange</fullName>
                </value>
                <value>
                    <fullName>Cancellation - Controllable</fullName>
                </value>
                <value>
                    <fullName>Cancellation - Uncontrollable</fullName>
                </value>
                <value>
                    <fullName>Cargo Services</fullName>
                </value>
                <value>
                    <fullName>CAR- Online Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>Carry - on - Lost</fullName>
                </value>
                <value>
                    <fullName>Carry - on - Lost &amp; Found</fullName>
                </value>
                <value>
                    <fullName>Catering - Meal Quality</fullName>
                </value>
                <value>
                    <fullName>Catering - Meal Quantity</fullName>
                </value>
                <value>
                    <fullName>Catering Service Complaints</fullName>
                </value>
                <value>
                    <fullName>Compensation - Baggage Mishandling</fullName>
                </value>
                <value>
                    <fullName>Compensation - Flight Cancellation</fullName>
                </value>
                <value>
                    <fullName>Compensation - NEGBAL</fullName>
                </value>
                <value>
                    <fullName>Compliment</fullName>
                </value>
                <value>
                    <fullName>Compliment Medical Assistance</fullName>
                </value>
                <value>
                    <fullName>Configuration Change</fullName>
                </value>
                <value>
                    <fullName>Contents Damaged-Domestic</fullName>
                </value>
                <value>
                    <fullName>Contents Damaged-International</fullName>
                </value>
                <value>
                    <fullName>Damage</fullName>
                </value>
                <value>
                    <fullName>Delay - Controllable</fullName>
                </value>
                <value>
                    <fullName>Delay - Uncontrollable</fullName>
                </value>
                <value>
                    <fullName>Denied Boarding</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Airport Services</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Cockpit</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Engineering/ MCC</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>FSC</fullName>
                </value>
                <value>
                    <fullName>Guest Error</fullName>
                </value>
                <value>
                    <fullName>In- Flight</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Legal/HR</fullName>
                </value>
                <value>
                    <fullName>Marketing/ Products</fullName>
                </value>
                <value>
                    <fullName>Reservation Administration</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
                <value>
                    <fullName>SalesRevenue</fullName>
                    <label>Sales/Revenue</label>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>SpiceVacation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Category__c</fullName>
        <label>Sub-Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Baggage Allowance</fullName>
                </value>
                <value>
                    <fullName>Baggage Open Condition</fullName>
                </value>
                <value>
                    <fullName>Bottle Broken</fullName>
                </value>
                <value>
                    <fullName>Conveyor Belt Issue</fullName>
                </value>
                <value>
                    <fullName>Customs/Immigration Issue</fullName>
                </value>
                <value>
                    <fullName>EBC Issue</fullName>
                </value>
                <value>
                    <fullName>Exchange Baggage / Taken By Passenger</fullName>
                </value>
                <value>
                    <fullName>Flight Status</fullName>
                </value>
                <value>
                    <fullName>Gate No-Show</fullName>
                </value>
                <value>
                    <fullName>Guest Error</fullName>
                </value>
                <value>
                    <fullName>InApplicable</fullName>
                </value>
                <value>
                    <fullName>Internet Booking</fullName>
                </value>
                <value>
                    <fullName>Invalid Complaint</fullName>
                </value>
                <value>
                    <fullName>Itinerary</fullName>
                </value>
                <value>
                    <fullName>Late Baggage Delivery</fullName>
                </value>
                <value>
                    <fullName>Left Behind</fullName>
                </value>
                <value>
                    <fullName>Level 4/DG Restrictions</fullName>
                </value>
                <value>
                    <fullName>LOPA - Voucher</fullName>
                </value>
                <value>
                    <fullName>LRT Issues</fullName>
                </value>
                <value>
                    <fullName>LRT Signed</fullName>
                </value>
                <value>
                    <fullName>MAAS Issue</fullName>
                </value>
                <value>
                    <fullName>Minor Damage</fullName>
                </value>
                <value>
                    <fullName>Misinformation</fullName>
                </value>
                <value>
                    <fullName>Mis-Information</fullName>
                </value>
                <value>
                    <fullName>Misuse - Credit Card/Credit Shell/Voucher</fullName>
                </value>
                <value>
                    <fullName>Nil Value Declared</fullName>
                </value>
                <value>
                    <fullName>No Show</fullName>
                </value>
                <value>
                    <fullName>No-Show</fullName>
                </value>
                <value>
                    <fullName>Offer/Sale Query</fullName>
                </value>
                <value>
                    <fullName>OND Short Connection</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sub_Department__c</fullName>
        <label>Sub-Department</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Travel Portals/Travel Agents</fullName>
                </value>
                <value>
                    <fullName>Customer Cases</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                </value>
                <value>
                    <fullName>Flight Status</fullName>
                </value>
                <value>
                    <fullName>Baggage allowance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DuplicateCaseController.cls
public with sharing class DuplicateCaseController {
    
    private ApexPages.StandardSetController standardController;
    public Case parentCase {get;set;}
    @TestVisible private case parentCaseRecord;
    private List<Case> duplicateCases = New List<Case>();
    
    public DuplicateCaseController(ApexPages.StandardSetController standardController)
    {
        parentCase = new Case();
        this.standardController = standardController;
    }
    
    public PageReference updateCases()
    {       
        // Get the selected records (optional, you can use getSelected to obtain ID's and do your own SOQL)
        
        
        if(parentCase.ParentId != null){
            
            parentCaseRecord = [select id, category__c, department__c,
                                sub_department__c, sub_category__c 
                                from case 
                                where id =: parentCase.ParentId];    
            
            
            List<Case> selectedCases = [select id, parentid, department__c, 
                                        category__c, sub_department__c, 
                                        sub_category__c 
                                        from case 
                                        where 
                                        id IN: standardController.getSelected()
                                       ];
            system.debug('standardController.getSelected()'+standardController.getSelected());
            if(standardController.getSelected()!=NULL){
                for(Case selectedCase : selectedCases)
                {
                  Case duplicateCase = New Case(Id = selectedCase.Id, ParentId = parentCaseRecord.Id,
                  Department__c = parentCaseRecord.Department__c,
                  Category__c = parentCaseRecord.Category__c,
                  Sub_Category__c = parentCaseRecord.Sub_Category__c,
                  Sub_Department__c = parentCaseRecord.Sub_Department__c,
                  Status = 'Duplicate - Closed');
                
                  duplicatecases.add(duplicateCase);
                    
                }
                 update duplicatecases;


            }else
                 {
                   ApexPages.addmessage(new ApexPages.message(ApexPages.severity.FATAL,'Please select case records'));                 
                 }
            
        }
        
        PageReference docancel = standardController.cancel();
  
        return docancel;
    }
 
}