objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Department__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AC not working</fullName>
                </value>
                <value>
                    <fullName>Add-ons Issue</fullName>
                </value>
                <value>
                    <fullName>Aircraft Interior</fullName>
                </value>
                <value>
                    <fullName>Ancillary Revenue</fullName>
                </value>
                <value>
                    <fullName>Atom IVR</fullName>
                </value>
                <value>
                    <fullName>Bad Landing</fullName>
                </value>
                <value>
                    <fullName>Bad Landing/Complaint</fullName>
                </value>
                <value>
                    <fullName>Baggage Exchange</fullName>
                </value>
                <value>
                    <fullName>Baggage Interchange</fullName>
                </value>
                <value>
                    <fullName>Cancellation - Controllable</fullName>
                </value>
                <value>
                    <fullName>Cancellation - Uncontrollable</fullName>
                </value>
                <value>
                    <fullName>Cargo Services</fullName>
                </value>
                <value>
                    <fullName>CAR- Online Bank Transfer</fullName>
                </value>
                <value>
                    <fullName>Carry - on - Lost</fullName>
                </value>
                <value>
                    <fullName>Carry - on - Lost &amp; Found</fullName>
                </value>
                <value>
                    <fullName>Catering - Meal Quality</fullName>
                </value>
                <value>
                    <fullName>Catering - Meal Quantity</fullName>
                </value>
                <value>
                    <fullName>Catering Service Complaints</fullName>
                </value>
                <value>
                    <fullName>Compensation - Baggage Mishandling</fullName>
                </value>
                <value>
                    <fullName>Compensation - Flight Cancellation</fullName>
                </value>
                <value>
                    <fullName>Compensation - NEGBAL</fullName>
                </value>
                <value>
                    <fullName>Compliment</fullName>
                </value>
                <value>
                    <fullName>Compliment Medical Assistance</fullName>
                </value>
                <value>
                    <fullName>Configuration Change</fullName>
                </value>
                <value>
                    <fullName>Contents Damaged-Domestic</fullName>
                </value>
                <value>
                    <fullName>Contents Damaged-International</fullName>
                </value>
                <value>
                    <fullName>Damage</fullName>
                </value>
                <value>
                    <fullName>Delay - Controllable</fullName>
                </value>
                <value>
                    <fullName>Delay - Uncontrollable</fullName>
                </value>
                <value>
                    <fullName>Denied Boarding</fullName>
                </value>
                <value>
                    <fullName>Rude Behavior</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Department</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Airport Services</fullName>
                </value>
                <value>
                    <fullName>Ancillary</fullName>
                </value>
                <value>
                    <fullName>Cargo</fullName>
                </value>
                <value>
                    <fullName>Catering</fullName>
                </value>
                <value>
                    <fullName>Cockpit</fullName>
                </value>
                <value>
                    <fullName>Customer Experience</fullName>
                </value>
                <value>
                    <fullName>Engineering/ MCC</fullName>
                </value>
                <value>
                    <fullName>Finance</fullName>
                </value>
                <value>
                    <fullName>FSC</fullName>
                </value>
                <value>
                    <fullName>Guest Error</fullName>
                </value>
                <value>
                    <fullName>In- Flight</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>Legal/HR</fullName>
                </value>
                <value>
                    <fullName>Marketing/ Products</fullName>
                </value>
                <value>
                    <fullName>Reservation Administration</fullName>
                </value>
                <value>
                    <fullName>Reservations</fullName>
                </value>
                <value>
                    <fullName>SalesRevenue</fullName>
                    <label>Sales/Revenue</label>
                </value>
                <value>
                    <fullName>Security</fullName>
                </value>
                <value>
                    <fullName>SpiceVacation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TriggerController__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To manage trigger using checkbox-make acive/deactive</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to activate/deactivate trigger</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerController</label>
</CustomObject>

classes/DuplicateCaseTest.cls
@isTest
public class DuplicateCaseTest {
    
    public static testmethod void testDuplicateCaseclose(){
        Test.startTest();
        
        TriggerController__c tController = new TriggerController__c();
        tController.Name = 'CaseTrigger';
        tcontroller.IsActive__c = true;
        insert tController;
        
        Case PreTestParentCase=new Case(Subject='Baggage lost',
                                     Description='Baggage lost',
                                     Type='Query',
                                     Department__c='Reservations',
                                     Category__c='Rude Behavior',
                                     Status='Open',
                                     Origin='Email'
                                    );
        
         insert PreTestParentCase;
        Case TestParentCase=new Case(Subject='Baggage lost',
                                     Description='Baggage lost',
                                     Type='Query',
                                     ParentId=PreTestParentCase.Id,
                                     Department__c='Reservations',
                                     Category__c='Rude Behavior',
                                     Status='Open',
                                     Origin='Email'
                                    );
        
         insert TestParentCase;
        
        List<Case> caseList=new List<Case>();
        Test.setCurrentPage(Page.MassUpdateasDuplicate);
        
                
        Case TestCase1=new Case(Subject='Baggage lost',
                                     Description='Baggage lost',
                                     Type='Query',
                                     Status='Open',
                                     Origin='Email'
                                    );
         caseList.add(TestCase1);
         //insert TestCase1;
          
        
         Case TestCase2=new Case(Subject='Baggage lost',
                                     Description='Baggage lost',
                                     Type='Query',
                                     Status='Open',
                                     Origin='Email'
                                    );
          caseList.add(TestCase2);
          
          insert caseList; 
        
        ApexPages.StandardSetController stdSetController = new ApexPages.StandardSetController(caseList);
        stdSetController.setSelected(caseList);  
        DuplicateCaseController  stdcontroller=new DuplicateCaseController(stdSetController);
        stdcontroller.parentCase =TestParentCase;
        stdcontroller.updateCases();
        
        Test.stopTest();              
    }
}