objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved by Central Coordinator</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Created_in_Navitaire__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Created in Navitaire</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Last_Name_AS__c</fullName>
        <label>Last Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Role__c</fullName>
        <label>Product/Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>API</fullName>
                </value>
                <value>
                    <fullName>API Corporate</fullName>
                </value>
                <value>
                    <fullName>CORT</fullName>
                </value>
                <value>
                    <fullName>HOL</fullName>
                </value>
                <value>
                    <fullName>IBM</fullName>
                </value>
                <value>
                    <fullName>LTC</fullName>
                </value>
                <value>
                    <fullName>STBF</fullName>
                </value>
                <value>
                    <fullName>TATA</fullName>
                </value>
                <value>
                    <fullName>TCPN</fullName>
                </value>
                <value>
                    <fullName>Web Travel Agent</fullName>
                </value>
                <value>
                    <fullName>APIC</fullName>
                </value>
                <value>
                    <fullName>GRP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Corporate</fullName>
        <active>true</active>
        <businessProcess>Corporate</businessProcess>
        <description>For Corporate leads</description>
        <label>Corporate</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/TriggerController__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To manage trigger using checkbox-make acive/deactive</description>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be used to activate/deactivate trigger</description>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerController</label>
</CustomObject>

classes/LeadTriggerTest.cls
@isTest
public class LeadTriggerTest {
    public static testMethod void TestLeadTrigger() {

        TriggerController__c tController = new TriggerController__c();
        tController.Name = 'LeadTrigger';
        tcontroller.IsActive__c = true;
        insert tController;

        TriggerController__c tController1 = new TriggerController__c();
        tController1.Name = 'AccountTrigger';
        tcontroller1.IsActive__c = true;
        insert tController1;

        Id corporateRecordTypeId = Schema.SObjectType.Lead.getRecordTypeInfosByName().get('Corporate').getRecordTypeId();

        Lead ld = new Lead();
        ld.LastName = 'Test';
        ld.Status = 'Open';
        ld.Company = 'ABC Industries';
        ld.Product_Role__c = 'TATA';
        ld.RecordTypeId = corporateRecordTypeId;
        ld.Last_Name_AS__c = 'Rakesh';
        ld.Approval_Status__c = 'Draft';
        insert ld;

        ld.Approval_Status__c = 'Approval by Central Coordinator';
        try{
            update ld;
        }catch(Exception ex){}

        ld.Approval_Status__c = 'Approved';
        ld.Created_in_Navitaire__c = TRUE;
        update ld;
    }
}